version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Build the React application
          command: npm run build
  deploy-job:
    docker:
      - image: circleci/node:6
    working_directory: ~/metro-elevator-frontend
    steps:
      - run:
          name: Install AWS CLI
          command: sudo apt-get install awscli
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync build/ s3://metro-elevator-frontend --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
