version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Build the React application
          command: npm run build
      - persist_to_workspace:
          root: ~/metro-elevator-frontend/build
          paths:
            - app
  deploy-job:
    docker:
      - image: circleci/node:6
    working_directory: ~/circleci-app
    steps:
      - attach_workspace:
          at: ~/circlecli-app/metro-elevator-frontend/build
      - run:
          name: Install AWS CLI
          command: sudo apt-get install awscli
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync metro-elevator-frontend/build/ s3://metro-elevator-frontend --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
