version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Build the React application
          command: npm run build
      - run:
          name: Install AWS CLI
          command: sudo apt-get install awscli
      - run:
          name: List all the files
          command: ls
      - run:
          name: Determine the PWD
          command: pwd
      - run:
          name: Deploy to S3
          command: aws s3 sync metro-elevator-frontend/build/ s3://metro-elevator-frontend --delete
